MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  DOMAIN_ADAPTATION_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 1024
  # RESNETS:
  #   BACKBONE_OUT_CHANNELS: 256
  RPN:
    # USE_FPN: True
    # # ANCHOR_STRIDE: (8, 16, 32, 64, 128)
    # ANCHOR_STRIDE: (4,8, 16, 32, 64)
    # PRE_NMS_TOP_N_TRAIN: 2000
    # PRE_NMS_TOP_N_TEST: 1000 #1000
    # POST_NMS_TOP_N_TEST: 1000
    # FPN_POST_NMS_TOP_N_TEST: 1000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
  ROI_BOX_HEAD:
    NUM_CLASSES: 9
  ROI_HEADS:
    # USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 256
  # ROI_BOX_HEAD:
  #   NUM_CLASSES: 2
  #   POOLER_RESOLUTION: 7
  #   POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
  #   POOLER_SAMPLING_RATIO: 2
  #   FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
  #   PREDICTOR: "FPNPredictor"
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    NMS: 0.3
  DA_HEADS:
    DA_IMG_GRL_WEIGHT: 0.1
    DA_INS_GRL_WEIGHT: 0.1
DATASETS:
  # TRAIN: ("cityscapes_car_train_cocostyle",)
  # SOURCE_TRAIN: ("cityscapes_car_train_cocostyle",)
  # TARGET_TRAIN: ("kitti_cocostyle",)
  # TEST: ("kitti_cocostyle",)
  # #TODO: jinlong
  # TARGET_TRAIN_negative: ("cityscapes_rain_car_trian_cocostyle",)
  TRAIN: ("cityscapes_fine_instanceonly_seg_train_cocostyle",)
  SOURCE_TRAIN: ("cityscapes_fine_instanceonly_seg_train_cocostyle",)
  TARGET_TRAIN: ("foggy_cityscapes_fine_instanceonly_seg_train_cocostyle",)
  TARGET_TRAIN_negative: ("rainy_cityscapes_fine_instanceonly_seg_train_cocostyle",)
  TEST: ("foggy_cityscapes_fine_instanceonly_seg_val_cocostyle",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
# SOLVER:
#   BASE_LR: 0.02
#   WEIGHT_DECAY: 0.0001
#   STEPS: (60000, 80000)
#   MAX_ITER: 90000

INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 1200
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1200
SOLVER:

  BASE_LR: 0.001 #fineturn= 0.0001
  WEIGHT_DECAY: 0.0005
  STEPS: (50000, 80000,100000)   #original: (50000, 80000)
  MAX_ITER: 120000  #original:70000   100000
  IMS_PER_BATCH: 2 #original:2
TEST:
  IMS_PER_BATCH: 1